{% set build_version = "0.35.0" %}

package:
  name: tensorflow-io
  version: {{ build_version }}

source:
  git_url: https://github.com/tensorflow/io.git
  git_rev: v{{ build_version }}
  patches:
    # 01xx - patch is specific to open-ce and will always be carried forward and not upstreamed
    - 0101-Build-fixed-on-ppc.patch            #[ppc64le]
    - 0102-Removed-aws_checksum_cpu_id-redefinition.patch #[ppc64le]
    - 0104-Fix-another-error-with-headers-not-found.patch
    - 0105-Boringssl-fixed-for-GCC-11.patch    #[c_compiler_version == "11.2.*"]
    - 0108-Fixed-upb.patch
    - 0109-Add-include-path-for-rpc-headers-from-libtirpc-devel.patch   #[ppc_arch == 'p10']
    - 0301-Updated-protobuf-to-4.21.patch
    - 0302-Fixed-Rename-from-bazel-toolchain-to-toolchains_llvm.patch

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

outputs:
  - name: tensorflow-io-gcs-filesystem
    script: build-tf-io-gcs-filesystem.sh
    requirements:
      build:
        - {{ compiler('c') }}      # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
      host:
        - git >=2.2
        - bazel {{ bazel }}
        - setuptools {{ setuptools }}
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
        - _tensorflow_select 1.0          #[build_type == 'cpu']
        - _tensorflow_select 2.0          #[build_type == 'cuda']
        - keras {{ keras }}
        - tensorflow-estimator {{ tensorflow }}
        - tensorboard {{ tensorboard }}
      run:
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
        - _tensorflow_select 1.0          #[build_type == 'cpu']
        - _tensorflow_select 2.0          #[build_type == 'cuda']
        - keras {{ keras }}
        - tensorflow-estimator {{ tensorflow }}
        - tensorboard {{ tensorboard }}

  - name: tensorflow-io
    script: build-tf-io.sh
    requirements:
      build:
        - {{ compiler('c') }}      # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
        - bazel {{ bazel }}
      host:
        - git >=2.2
        - setuptools {{ setuptools }}
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
        - _tensorflow_select 1.0          #[build_type == 'cpu']
        - _tensorflow_select 2.0          #[build_type == 'cuda']
        - keras {{ keras }}
        - tensorflow-estimator {{ tensorflow }}
        - tensorboard {{ tensorboard }}
      run:
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
        - _tensorflow_select 1.0          #[build_type == 'cpu']
        - _tensorflow_select 2.0          #[build_type == 'cuda']
        - keras {{ keras }}
        - tensorflow-estimator {{ tensorflow }}
        - tensorboard {{ tensorboard }}


test:
  commands:
    - export TF_USE_MODULAR_FILESYSTEM=1; python -c "import tensorflow_io_gcs_filesystem as tfio; import tensorflow_io;"

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: Dataset, streaming, and file system extensions
  description: |
    TensorFlow I/O is a collection of file systems and file formats that are
    not available in TensorFlow's built-in support.
  dev_url: https://github.com/tensorflow/io
  doc_url: https://github.com/tensorflow/io/tree/v{{ build_version }}/docs

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
