{% set build_version = "0.27.0" %}

package:
  name: tensorflow-io
  version: {{ build_version }}

source:
  git_url: https://github.com/tensorflow/io.git
  git_rev: v{{ build_version }}
  patches:
    # 01xx - patch is specific to open-ce and will always be carried forward and not upstreamed
    - 0101-Build-fixed-on-ppc.patch            #[ppc64le]
    - 0104-Fix-another-error-with-headers-not-found.patch
    - 0105-Boringssl-fixed-for-GCC-11.patch    #[c_compiler_version == "11.2.*"]
    - 0106-fix-for-py310.patch

    - 0301-Updated-protobuf-to-3.19.patch
    - 0302-Fix-libwebp-linking-errors.patch

build:
  number: 1
  string: h{{ PKG_HASH }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

outputs:
  - name: tensorflow-io-gcs-filesystem
    script: build-tf-io-gcs-filesystem.sh
    requirements:
      build:
        - {{ compiler('c') }}      # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
      host:
        - git >=2.2
        - bazel {{ bazel }}
        - setuptools {{ setuptools }}
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
        - keras {{ keras }}
        - tensorflow-estimator {{ tensorflow }}
        - tensorboard {{ tensorboard }}
      run:
        - python {{ python }}
        - numpy {{ numpy }}

  - name: tensorflow-io
    script: build-tf-io.sh
    requirements:
      build:
        - {{ compiler('c') }}      # [ ppc_arch != "p10"]
        - {{ compiler('cxx') }}    # [ ppc_arch != "p10"]
        - bazel {{ bazel }}
      host:
        - git >=2.2
        - setuptools {{ setuptools }}
        - python {{ python }}
        - numpy {{ numpy }}
        - tensorflow-base {{ tensorflow }}
      run:
        - python {{ python }}
        - numpy {{ numpy }}

test:
  requires:
    - tensorflow-base {{ tensorflow }}
  imports:
    - tensorflow_io_gcs_filesystem
    - tensorflow_io

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  license_file: {{ SRC_DIR }}/LICENSE
  summary: Dataset, streaming, and file system extensions
  description: |
    TensorFlow I/O is a collection of file systems and file formats that are
    not available in TensorFlow's built-in support.
  dev_url: https://github.com/tensorflow/io
  doc_url: https://github.com/tensorflow/io/tree/v{{ build_version }}/docs

test:
  requires:
    - tensorflow-base {{ tensorflow }}
  commands:
    - export TF_USE_MODULAR_FILESYSTEM=1; python -c "import tensorflow_io_gcs_filesystem as tfio;"

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
